version: 2.1

orbs:
  architect: giantswarm/architect@5.1.0

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build-auth0ctl
          binary: auth0ctl
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
